version: '3'

services:
  next-app:
    container_name: next-app
    build:
      context: .
      dockerfile: Dockerfile

    # Set environment variables directly in the docker-compose file
    environment:
      ENV_VARIABLE: ${ENV_VARIABLE}
      NEXT_PUBLIC_ENV_VARIABLE: ${NEXT_PUBLIC_ENV_VARIABLE}

    # Set envrionment variables based on the .env file
    env_file:
      - .env
    volumes:
      - ./src:/app/src
      - ./public:/app/public
    restart: always
    ports:
      - 3000:3000
    networks:
      - my_network
    depends_on:
      - postgres

  postgres:
    container_name: db
    image: postgres:latest
    environment:
      DATABASE_URL: ${DATABASE_URL}
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - 5432:5432
    networks:
      - my_network
    volumes:
      - postgres-data:/var/lib/postgresql/data

  # Add more containers below (nginx, postgres, etc.)
volumes:
  postgres-data:
# Define a network, which allows containers to communicate
# with each other, by using their container name as a hostname
networks:
  my_network:
    external: true