version: "3"

services:
  next-app:
    container_name: next-app
    build:
      context: .
      dockerfile: Dockerfile

    # Set environment variables directly in the docker-compose file
    environment:
      ENV_VARIABLE: ${ENV_VARIABLE}
      NEXT_PUBLIC_ENV_VARIABLE: ${NEXT_PUBLIC_ENV_VARIABLE}

    # Set envrionment variables based on the .env file
    env_file:
      - .env
    volumes:
      - ./src:/app/src
      - ./public:/app/public
    restart: always
    ports:
      - 3000:3000
    networks:
      - my_network
    depends_on:
      - postgres

  postgres:
    container_name: next-db
    image: postgres:15
    environment:
      DATABASE_URL: ${DATABASE_URL}
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - 5432:5432
    networks:
      - my_network
    volumes:
      - postgres-data:/var/lib/postgresql/data

  ai-service:
    container_name: ai-service
    build:
      context: ./ai-service
      dockerfile: ./Dockerfile
    env_file:
      - .env
    volumes:
      - .:/article_creation
    restart: always
    ports:
      - 8000:8000
    networks:
      - my_network
    command: uvicorn article_creation.main:app --host 0.0.0.0 --reload
    depends_on:
      - postgres
      - next-app

volumes:
  postgres-data:

networks:
  my_network:
    external: true
